import {
  FaUserCog,
  FaTh,
  FaUsers,
  FaComment,
  FaTelegramPlane,
  FaTasks,
  FaCogs,
} from 'react-icons/fa';

export const menuItems = [
  {
    id: 1,
    name: 'Perfil',
    route: '/profile',
    menu: true,
    icon: FaUserCog,
    feature: false,
    description: 'Configuración del perfil del usuario',
    role: ['admin', 'user'],
  },

  {
    id: 2,
    name: 'Dashboard',
    route: '/dashboard',
    menu: true,
    feature: false,
    icon: FaTh,
    description: 'Dashboard',
    role: ['admin', 'user'],
  },
  {
    id: 3,
    name: 'Usuarios',
    route: '/users',
    menu: true,
    feature: false,
    icon: FaUsers,
    description: 'Configuración de usuarios del sistema',
    role: ['admin'],
  },
  {
    id: 7,
    name: 'Secciones',
    route: '/config-sections',
    menu: true,
    feature: false,
    icon: FaCogs,
    description: 'Configuración de secciones del sistema',
    role: ['admin'],
  },
  {
    id: 4,
    name: 'Contactos',
    route: '/contacts',
    menu: true,
    feature: false,
    icon: FaComment,
    description: 'Contactos recibidos desde la página web',
    role: ['admin', 'user'],
  },
  {
    id: 5,
    name: 'Suscriptores',
    route: '/subscribers',
    menu: true,
    feature: false,
    icon: FaTelegramPlane,
    description: 'Suscripciones al newsletter recibidos desde la página web',
    role: ['admin', 'user'],
  },
  {
    id: 6,
    name: 'Secciones',
    route: '/sections',
    menu: true,
    feature: false,
    icon: FaTasks,
    description: 'Configuración de secciones de la página web',
    role: ['admin', 'user'],
  },
];
